# This unfortunately must be named this.

env:
  AMP_INSTANCE: space-factory

import_docker_builder:
  # Run directly on the system to snag the AMP data
  freshen_script:
    # Remove previous run stuff
    - rm -rf tmp
  snag_script:
    # Copy and extract the backup
    - mkdir tmp
    - unzip ~amp/.ampdata/instances/$AMP_INSTANCE/Backups/$filename -d ./tmp
    # - unzip amp-backup.zip -d ./tmp


mapshot_task:
  depends_on:
    - import
  container:
    dockerfile: mapshot.Dockerfile
  setup_script:
    - python3 ./pre-filter.py --mods=tmp/config/mods
    # Take the data in tmp and put it in places mapshot is happy with
    - mkdir -p /opt/factorio/mods /opt/factorio/saves
    - cp tmp/config/mods/* /opt/factorio/mods
    - cp tmp/saves/* /opt/factorio/saves
  gen_script:
    # Actually render the map (Cirrus ignores entrypoint)
    - xvfb-run "--server-args=-fbdir ./tmp +extension GLX +render" --error-file /dev/stdout -- mapshot-render || true
    # FIXME: Autodetect specific root
    - python3 ./post-filter.py /opt/factorio/script-output/mapshot/default/
    - mv /opt/factorio/script-output/mapshot/default/ mapshot/
  map_artifacts:
    path: "mapshot/**"

# TODO: Surfaces generation?
